version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-21-247-176.compute-1.amazonaws.com
            database: d9rq7js44634bn
            schema: public
            user: omwdbdinynsepm
            password: 19b1b14f9e10d6eb0f8431f1677a1a70755d664566ad86e3d0faa823c5891d53
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true